---
- hosts: db
  vars:
        db_host: tf-20161214025627430472700js3.c1on7atrmini.us-west-2.rds.amazonaws.com
  tasks:
    - name: include secrets
      include_vars: vault.yml

    - name: copy MariaDB repository from controller
      become : yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: update MariaDB server using yum
      become: yes
      yum: name={{ item }} update_cache=yes state=present
      with_items:
        - MariaDB-client


    - name: copy and unpack db.tgz from controller
      unarchive: src=db/db.tgz dest=~/ mode=0777

    - name: run database.sh using "{{ service_dir }}"
      command: ./make_databases.sh {{ db_password }} {{ db_host }} chdir=~/db
      ignore_errors: True
